### ISSUE TITLE
TOO MUCH RAM USAGE

### ISSUE THREAD

**Issue by TheKamboy** [HRK-EXEX/H-Slice#3]
### Describe your bug here.

My laptop is not the most powerful thing (Intel core i5, 8 GB ram), but it could handle the old version of the engine.

Tried to get a recording, but it used up so much ram, it couldn't even play a second of the song.

Without recording I could get it to play Sonorous 3 (Jordans Chart) until the really spammy part, then it crashed.

https://github.com/user-attachments/assets/67caf90d-33b5-4faa-9cd5-ca80c1a9c981

### Command Prompt/Terminal logs ()

```bash
In the video
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by HRK-EXEX** [comment]
did u killed the process urself???
also it seems loaded successfully but why

anyway this version not for overcharted,
it's just for playing as normal chart for the moment

just wait 0.2.0 if u wanna play stupidly big chart

**Comment by TheKamboy** [comment]
> did u kill the process urself??? also it seems loaded successfully but why
> 
> anyway this version not for overcharted, it's just for playing as normal chart for the moment
> 
> just wait 0.2.0 if u wanna play stupidly big chart

1. No it didn't kill itself, that message appears for me when the app crashes
2. Alright I'll wait

**Comment by HRK-EXEX** [comment]
ok then i'll close
