### ISSUE TITLE
The chart editor notes are all left

### ISSUE THREAD

**Issue by TheKamboy** [HRK-EXEX/H-Slice#4]
### Describe your bug here.

No I didn't fake it, it is all lefts for me.
![screenshot_20241222_222147](https://github.com/user-attachments/assets/a1cc878d-ea1c-4848-a010-584bda58acab)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheKamboy** [comment]
Here's a video showing that the chart editor uses all lefts, but not in game

https://drive.google.com/file/d/1gS7hs1pjInFZObNs8k9WE5yJZTCmo8Jq/view?usp=sharing

**Comment by HRK-EXEX** [comment]
i checked that bug on happen in 0.1.1
so i'll fix it and prepare next prerelease (0.1.2)
thanks to feedback to us!

**Comment by TheKamboy** [comment]
> i checked that bug on happen in 0.1.1 so i'll fix it and prepare next prerelease (0.1.2) thanks to feedback to us!

Yeah, no problem!
