### ISSUE TITLE
Health Bar icons don't move

### ISSUE THREAD

**Issue by TheKamboy** [HRK-EXEX/H-Slice#5]
### Describe your bug here.

For some reason, the health bar icons don't move an inch, even if health is full, or low.
![screenshot_20241226_112139](https://github.com/user-attachments/assets/fcbde205-c3b4-4997-8f4e-94a9d409d5ca)

I checked if it was my scripts, but the bug happens, even without scripts.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by JordanSantiagoYT** [comment]
time to update this, the health bar only updates if you have "Over Health" turned on

**Comment by HRK-EXEX** [comment]
I've comfirmed the bug and fixed it.
Please wait for releasing 0.1.3.

**Comment by HRK-EXEX** [comment]
0.1.3 has released
